### ISSUE TITLE
removeCountryCodeFromMask results in incorrect phone mask for US and national number

### ISSUE THREAD

**Issue by woelmer** [bottlepay/flutter_libphonenumber#22]
Calling this text formatter:

`LibPhonenumberTextFormatter(
              country: usCountry,
              PhoneNumberFormat.national)`

Will result in the following mask "0) 000-0000"
It should be "(000) 000-0000"

There are a couple problems:

1. input_formatter.dart line 28: removeCountryCodeFromMask gets set to true even though the phone number is a national number and the inputContainsCountryCode is false.

2. Once removeCountryCodeFromMask is true country_data.dart line 188 will remove three characters from the beginning of the national mask therefore chopping off the area code portion of the national phone number mask.

**Comment by mockturtl** [comment]
@acoutts This bug is still present in 2.1.5.

In my use case, the "country picker" is a separate dropdown / bottom sheet, so the input text field will **not** include the "pluscode" ("national" format; `inputContainsCountryCode` is false).

Since the mask is "national" (already excludes the pluscode), I believe it's redundant to trim it by taking a [substring](https://github.com/acoutts/flutter_libphonenumber/blob/flutter_libphonenumber-v2.1.5/packages/flutter_libphonenumber_platform_interface/lib/src/types/country_with_phone_code.dart#L149).

**Comment by mockturtl** [comment]
I forked the repo to fix this issue for my use case.  Feedback / PR's welcome.

[`fix-22-national-mask`](
https://github.com/mockturtl/flutter_libphonenumber_platform_interface/tree/fix-22-national-mask)

```yaml
dependency_overrides:
  flutter_libphonenumber_platform_interface: #https://github.com/acoutts/flutter_libphonenumber/issues/22
    git:
      url: https://github.com/mockturtl/flutter_libphonenumber_platform_interface
      ref: fix-22-national-mask
```
